In [ ]:
#Sirve para comparar valores de variables entre s√≠
import pandas as pd

In [ ]:
filename='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DV0101EN/labs/Data_Files/Canada.xlsx' 
df_can=pd.read_excel( filename, sheet_name="Canada by Citizenship", skiprows=range(20), skipfooter=2 )

df_can.rename(columns={"OdName":"Country"},inplace=True)
df_can.set_index("Country",inplace=True)
df_can["Total"]=df_can[1980]+df_can[1981]+df_can[1982]+df_can[1983]+df_can[1984]+df_can[1985]+df_can[1986]+df_can[1987]+df_can[1988]+df_can[1989]+df_can[1990]+df_can[1991]+df_can[1992]+df_can[1993]+df_can[1994]+df_can[1995]+df_can[1996]+df_can[1997]+df_can[1998]+df_can[1999]+df_can[2000]+df_can[2001]+df_can[2002]+df_can[2003]+df_can[2004]+df_can[2005]+df_can[2006]+df_can[2007]+df_can[2008]+df_can[2009]+df_can[2010]+df_can[2011]+df_can[2012]+df_can[2013]
df_can.head()

                      Type    Coverage  AREA AreaName  ...  2011  2012  2013  Total
Country                                                ...
Afghanistan     Immigrants  Foreigners   935     Asia  ...  2203  2635  2004  58639
Albania         Immigrants  Foreigners   908   Europe  ...   539   620   603  15699
Algeria         Immigrants  Foreigners   903   Africa  ...  4325  3774  4331  69439
American Samoa  Immigrants  Foreigners   909  Oceania  ...     0     0     0      6
Andorra         Immigrants  Foreigners   908   Europe  ...     0     1     1     15

[5 rows x 43 columns]

In [ ]:
df_total=pd.DataFrame()
years=list(range(1980,2014))

df_total=df_can.groupby(years).sum().groupby(level=0).cumsum()
df_total

KeyError: ignored